### ISSUE TITLE
[BACKEND] messages

### ISSUE THREAD

**Issue by Jcjacky** [fsxfreak/club-suite#260]
ERROR: test_post (suite.tests.test_view_event_edit.ViewEventEditTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jcjac/CSE110/cse-env/club-suite/clubsuite/suite/tests/test_view_event_edit.py", line 63, in test_post
    response=EventEdit.as_view()(request,club_id=self.club.pk,event_id=self.event.pk)
  File "/home/jcjac/CSE110/cse-env/lib/python3.4/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/jcjac/CSE110/cse-env/lib/python3.4/site-packages/django/contrib/auth/mixins.py", line 116, in dispatch
    return super(UserPassesTestMixin, self).dispatch(request, *args, **kwargs)
  File "/home/jcjac/CSE110/cse-env/lib/python3.4/site-packages/django/contrib/auth/mixins.py", line 56, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "/home/jcjac/CSE110/cse-env/lib/python3.4/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/jcjac/CSE110/cse-env/club-suite/clubsuite/suite/views/view_event_edit.py", line 45, in post
    messages.add_message(request, messages.SUCCESS, 'Successfully edited event.')
  File "/home/jcjac/CSE110/cse-env/lib/python3.4/site-packages/django/contrib/messages/api.py", line 28, in add_message
    'You cannot add messages without installing '
django.contrib.messages.api.MessageFailure: You cannot add messages without installing django.contrib.messages.middleware.MessageMiddleware

Its telling me to install `django.contrib.messages.middleware.MessageMiddleware`, should this software be included in the requirements.txt?

**Comment by Jcjacky** [comment]
Noticed that this is already a part of settings.py

According to this: http://stackoverflow.com/questions/39301092/wsgirequest-object-has-no-attribute-session-multiple-app

The order of middleware is important.

**Comment by Jcjacky** [comment]
nvm, django testing framework doesn't support middleware
