### ISSUE TITLE
[BACKEND] object has no attribute "session"

### ISSUE THREAD

**Issue by Jcjacky** [fsxfreak/club-suite#261]
======================================================================
ERROR: test_post_edit_password (suite.tests.test_view_account.View_Account_TestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jcjac/CSE110/cse-env/club-suite/clubsuite/suite/tests/test_view_account.py", line 45, in test_post_edit_password
    response=Account.as_view()(request)
  File "/home/jcjac/CSE110/cse-env/lib/python3.4/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/jcjac/CSE110/cse-env/lib/python3.4/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/jcjac/CSE110/cse-env/club-suite/clubsuite/suite/views/view_account.py", line 33, in post
    update_session_auth_hash(request, form2.user)
  File "/home/jcjac/CSE110/cse-env/lib/python3.4/site-packages/django/contrib/auth/__init__.py", line 219, in update_session_auth_hash
    request.session[HASH_SESSION_KEY] = user.get_session_auth_hash()
AttributeError: 'WSGIRequest' object has no attribute 'session'

Error when testing "change password"

According to this: http://stackoverflow.com/questions/39301092/wsgirequest-object-has-no-attribute-session-multiple-app

The order of middleware is important.

**Comment by Jcjacky** [comment]
nvm, django testing framework doesn't support middleware
